/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.ClienteDAO;
import dao.CompraDAO;
import dao.ItemDAO;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.TimeZone;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import model.Cliente;
import model.Compra;
import model.Item;

/**
 *
 * @author eric
 */
public class JFormCompra extends javax.swing.JFrame {

    /**
     * Creates new form JFormCompra
     */
    public JFormCompra() {
        initComponents();
        setLocationRelativeTo(null);
        preencherTabela();
        
        relogioDisplay();
        
        jcomboClientes();
        jcomboItens();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbClientes = new javax.swing.JComboBox<>();
        cbItens = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblDataHora = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblIdCliente = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblIdItem = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        lblEstoque = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCompra = new javax.swing.JTable();
        btnComprar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        lblValor = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();

        setTitle("Menu Compras");
        setResizable(false);
        setSize(new java.awt.Dimension(694, 515));

        cbClientes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbClientesItemStateChanged(evt);
            }
        });

        cbItens.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbItensItemStateChanged(evt);
            }
        });

        jLabel1.setText("Cliente");

        jLabel2.setText("Item");

        jLabel4.setText("Quantidade");

        jLabel3.setText("Data e Hora");

        jLabel5.setText("ID Cliente: ");

        lblIdCliente.setText("0");

        jLabel7.setText("Id Item:");

        lblIdItem.setText("0");

        txtQuantidade.setText("0");
        txtQuantidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtQuantidadeKeyReleased(evt);
            }
        });

        jLabel8.setText("Estoque:");

        lblEstoque.setText("0");

        tbCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Cliente", "Item", "Quantidade", "Data e Hora"
            }
        ));
        jScrollPane1.setViewportView(tbCompra);

        btnComprar.setText("Comprar");
        btnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        jLabel6.setText("Valor");

        lblValor.setText("0.0");

        jLabel10.setText("Total a pagar:");

        lblTotal.setText("0.0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblIdCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(cbClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblIdItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(cbItens, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnComprar)
                                .addGap(18, 18, 18)
                                .addComponent(btnExcluir)
                                .addGap(51, 51, 51)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblValor)
                                .addGap(17, 17, 17)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(jLabel4))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addGap(18, 18, 18)
                                                .addComponent(lblEstoque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel10)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(0, 0, Short.MAX_VALUE)))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(lblDataHora, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnSair)))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDataHora, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbItens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(lblIdCliente)
                        .addComponent(jLabel7)
                        .addComponent(lblIdItem))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(lblEstoque)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnExcluir)
                        .addComponent(btnSair)
                        .addComponent(lblValor)
                        .addComponent(jLabel10)
                        .addComponent(lblTotal)
                        .addComponent(jLabel6))
                    .addComponent(btnComprar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbClientesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbClientesItemStateChanged
        // TODO add your handling code here:
        Cliente cliente = (Cliente) cbClientes.getSelectedItem();
        
        lblIdCliente.setText("" + cliente.getId());
        
    }//GEN-LAST:event_cbClientesItemStateChanged

    private void cbItensItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbItensItemStateChanged
        // TODO add your handling code here:
        Item item = (Item) cbItens.getSelectedItem();
        
        lblIdItem.setText("" + item.getId());
        lblEstoque.setText("" + item.getEstoque());
        lblValor.setText("" + item.getValor());
        
    }//GEN-LAST:event_cbItensItemStateChanged

    private void btnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarActionPerformed
        // TODO add your handling code here:
        
        if(!txtQuantidade.getText().equals("")){
            
            int q = Integer.parseInt(txtQuantidade.getText());
            int e = Integer.parseInt(lblEstoque.getText());
            int baixa = e - q;

            if(q > 0 && q < e) {

                Cliente c = new Cliente();
                c.setId(Integer.parseInt(lblIdCliente.getText()));

                Item i = new Item();
                i.setId(Integer.parseInt(lblIdItem.getText()));
                i.setEstoque(e);

                Compra compra = new Compra();
                compra.setCliente(c);
                compra.setItem(i);
                compra.setQtd(q);

                CompraDAO dao = new CompraDAO();
                dao.insert(compra);

                JOptionPane.showMessageDialog(null, "Compra realizada com sucesso!");

                txtQuantidade.setText("0");
                lblEstoque.setText("" + baixa);

                preencherTabela();

            }
            else {
                JOptionPane.showMessageDialog(null, "Quantidade incorreta...");
            }
        }
        else {
            JOptionPane.showMessageDialog(null, "Informe a Quandidade");
        }
        
    }//GEN-LAST:event_btnComprarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        int linha = tbCompra.getSelectedRow();
        
        if(linha > -1){
            Compra compra = new Compra();
            compra.setCodigo(Long.parseLong(tbCompra.getValueAt(linha, 0).toString()));
            
            CompraDAO dao = new CompraDAO();
            dao.delete(compra);
            
            JOptionPane.showMessageDialog(null, "Compra removida da lista!");
            preencherTabela();
            
        } else {
            JOptionPane.showMessageDialog(null, "Seleciona uma linha da tabela!");
        }
        
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void txtQuantidadeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuantidadeKeyReleased
        // TODO add your handling code here:
        
        
        if(!(txtQuantidade.getText().equals(""))){
            
            int q = Integer.parseInt(txtQuantidade.getText());
            int e = Integer.parseInt(lblEstoque.getText());
            double valor = Double.parseDouble(lblValor.getText());
            
            if(q < e){

                lblTotal.setText("" + ((double)q * valor));
            
            } else {
                
                JOptionPane.showMessageDialog(null, "Quantidade limite é " + (--e));
                txtQuantidade.setText("" + e);
                lblTotal.setText("" + ((double)e * valor));
            }
               
        }
        
    }//GEN-LAST:event_txtQuantidadeKeyReleased
    
    private void preencherTabela(){
        
        DefaultTableModel modelo = (DefaultTableModel) tbCompra.getModel();
        modelo.setNumRows(0);
        
        CompraDAO dao = new CompraDAO();
        
        for(Compra c : dao.selectCompra()){
            
            Object[] dados = {
              c.getCodigo(),
              c.getCliente().getNome(),
              c.getItem().getDescricao(),
              c.getQtd(),
              c.getDataHora()
            };
            
            modelo.addRow(dados);
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    
    private void jcomboClientes(){
        
        ClienteDAO cliente = new ClienteDAO();
        
        for(Cliente c : cliente.selectCliente()){
            cbClientes.addItem(c); // pega o valor do metodo toString()
        }
    }
    
    private void jcomboItens(){
        
        ItemDAO item = new ItemDAO();
        
        for(Item i : item.selectItem()){
            cbItens.addItem(i);
        }
        
    }
    
    
    private void relogioDisplay(){
        
        Timer t = new Timer(1000, new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent ae) {
                Calendar cal = Calendar.getInstance(TimeZone.getTimeZone("Brazil/East"));
                
                String hr = "" + cal.get(Calendar.HOUR_OF_DAY);
                String min = "" + cal.get(Calendar.MINUTE);
                String sec = "" + cal.get(Calendar.SECOND);
                
               Date data = new Date();
               
               DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
               
               
                lblDataHora.setText(df.format(data) + " | " + hr + " : " + min +" : " + sec);
            }
            
        });
        t.start();
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFormCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFormCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFormCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFormCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFormCompra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComprar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnSair;
    private javax.swing.JComboBox<Object> cbClientes;
    private javax.swing.JComboBox<Object> cbItens;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDataHora;
    private javax.swing.JLabel lblEstoque;
    private javax.swing.JLabel lblIdCliente;
    private javax.swing.JLabel lblIdItem;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblValor;
    private javax.swing.JTable tbCompra;
    private javax.swing.JTextField txtQuantidade;
    // End of variables declaration//GEN-END:variables
}
